version: '3'
services:
  # API
  api:
    build: backend/.
    volumes:
      - './backend/:/var/www/html'
    command: bash -c "npm install && npm run start:debug"
    ports:
      - 3000:3000
    restart: unless-stopped

  # FRONTEND
  frontend:
    build: frontend/.
    command: http-server --p 8081 dist
    container_name: frontend
    ports:
      - 9001:8081
    volumes:
      - './frontend:/app'